# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class DemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetVersion = channel.unary_unary(
        '/Demo/GetVersion',
        request_serializer=demo__pb2.MsgHead.SerializeToString,
        response_deserializer=demo__pb2.Version.FromString,
        )
    self.GetProcesses = channel.unary_stream(
        '/Demo/GetProcesses',
        request_serializer=demo__pb2.MsgHead.SerializeToString,
        response_deserializer=demo__pb2.ProcessInfo.FromString,
        )
    self.GetCPUPercent = channel.stream_stream(
        '/Demo/GetCPUPercent',
        request_serializer=demo__pb2.ProcessPid.SerializeToString,
        response_deserializer=demo__pb2.ProcessCPUPercent.FromString,
        )


class DemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetProcesses(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCPUPercent(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetVersion': grpc.unary_unary_rpc_method_handler(
          servicer.GetVersion,
          request_deserializer=demo__pb2.MsgHead.FromString,
          response_serializer=demo__pb2.Version.SerializeToString,
      ),
      'GetProcesses': grpc.unary_stream_rpc_method_handler(
          servicer.GetProcesses,
          request_deserializer=demo__pb2.MsgHead.FromString,
          response_serializer=demo__pb2.ProcessInfo.SerializeToString,
      ),
      'GetCPUPercent': grpc.stream_stream_rpc_method_handler(
          servicer.GetCPUPercent,
          request_deserializer=demo__pb2.ProcessPid.FromString,
          response_serializer=demo__pb2.ProcessCPUPercent.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Demo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
