# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndemo.proto\"\'\n\x07MsgHead\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08hostname\x18\x02 \x01(\t\"&\n\x07Version\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\t\"(\n\x0bProcessInfo\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\nProcessPid\x12\x0b\n\x03pid\x18\x01 \x01(\x03\"E\n\x11ProcessCPUPercent\x12\x1b\n\x05pinfo\x18\x01 \x01(\x0b\x32\x0c.ProcessInfo\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x01\x32\x8e\x01\n\x04\x44\x65mo\x12\"\n\nGetVersion\x12\x08.MsgHead\x1a\x08.Version\"\x00\x12*\n\x0cGetProcesses\x12\x08.MsgHead\x1a\x0c.ProcessInfo\"\x00\x30\x01\x12\x36\n\rGetCPUPercent\x12\x0b.ProcessPid\x1a\x12.ProcessCPUPercent\"\x00(\x01\x30\x01\x62\x06proto3')
)




_MSGHEAD = _descriptor.Descriptor(
  name='MsgHead',
  full_name='MsgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MsgHead.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname', full_name='MsgHead.hostname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=53,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Version.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='Version.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=93,
)


_PROCESSINFO = _descriptor.Descriptor(
  name='ProcessInfo',
  full_name='ProcessInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='ProcessInfo.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProcessInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=135,
)


_PROCESSPID = _descriptor.Descriptor(
  name='ProcessPid',
  full_name='ProcessPid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='ProcessPid.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=162,
)


_PROCESSCPUPERCENT = _descriptor.Descriptor(
  name='ProcessCPUPercent',
  full_name='ProcessCPUPercent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pinfo', full_name='ProcessCPUPercent.pinfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_percent', full_name='ProcessCPUPercent.cpu_percent', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=233,
)

_PROCESSCPUPERCENT.fields_by_name['pinfo'].message_type = _PROCESSINFO
DESCRIPTOR.message_types_by_name['MsgHead'] = _MSGHEAD
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['ProcessInfo'] = _PROCESSINFO
DESCRIPTOR.message_types_by_name['ProcessPid'] = _PROCESSPID
DESCRIPTOR.message_types_by_name['ProcessCPUPercent'] = _PROCESSCPUPERCENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgHead = _reflection.GeneratedProtocolMessageType('MsgHead', (_message.Message,), dict(
  DESCRIPTOR = _MSGHEAD,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:MsgHead)
  ))
_sym_db.RegisterMessage(MsgHead)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), dict(
  DESCRIPTOR = _VERSION,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:Version)
  ))
_sym_db.RegisterMessage(Version)

ProcessInfo = _reflection.GeneratedProtocolMessageType('ProcessInfo', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSINFO,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:ProcessInfo)
  ))
_sym_db.RegisterMessage(ProcessInfo)

ProcessPid = _reflection.GeneratedProtocolMessageType('ProcessPid', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSPID,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:ProcessPid)
  ))
_sym_db.RegisterMessage(ProcessPid)

ProcessCPUPercent = _reflection.GeneratedProtocolMessageType('ProcessCPUPercent', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSCPUPERCENT,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:ProcessCPUPercent)
  ))
_sym_db.RegisterMessage(ProcessCPUPercent)



_DEMO = _descriptor.ServiceDescriptor(
  name='Demo',
  full_name='Demo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=236,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVersion',
    full_name='Demo.GetVersion',
    index=0,
    containing_service=None,
    input_type=_MSGHEAD,
    output_type=_VERSION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProcesses',
    full_name='Demo.GetProcesses',
    index=1,
    containing_service=None,
    input_type=_MSGHEAD,
    output_type=_PROCESSINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCPUPercent',
    full_name='Demo.GetCPUPercent',
    index=2,
    containing_service=None,
    input_type=_PROCESSPID,
    output_type=_PROCESSCPUPERCENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMO)

DESCRIPTOR.services_by_name['Demo'] = _DEMO

# @@protoc_insertion_point(module_scope)
